[2021-11-07 08:51:03,910: INFO: stage_01_prepare]: 
********************
[2021-11-07 08:51:03,910: INFO: stage_01_prepare]: >>>>> stage one started <<<<<
[2021-11-07 08:51:03,910: ERROR: stage_01_prepare]: [Errno 2] No such file or directory: 'config/config.yaml'
Traceback (most recent call last):
  File "src/stage_01_prepare.py", line 31, in <module>
    main(config_path=parsed_args.config,params_path=parsed_args.params)
  File "src/stage_01_prepare.py", line 19, in main
    config=read_yaml(config_path)
  File "c:\users\kisho\downloads\dvc-nlp\nlp-dvc\src\utils\common.py", line 8, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2021-11-07 08:51:24,652: INFO: stage_01_prepare]: 
********************
[2021-11-07 08:51:24,652: INFO: stage_01_prepare]: >>>>> stage one started <<<<<
[2021-11-07 08:51:24,652: INFO: stage_01_prepare]: >>>>> stage one completed! all the data are saved in local <<<<<n
